name: model-smart-bins
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    # optionally use a convenient Ubuntu LTS + CUDA + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro 
    
          git fetch --prune
          dvc metrics diff --show-md master > report.md

          echo "## Model Metrics" > report.md
          cat predictor/assets/results/metrics/metrics.json >> report.md

          # Add figure
          echo "## Forecast" >> report.md
          cml-publish predictor/assets/results/plots/forecast.png --md >>report.md

          cml-send-comment report.md

